"""p0 fix payment columns

Revision ID: 0c722739a556
Revises: 0f1501bac9b8
Create Date: 2026-09-25 15:41:40.085902
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0c722739a556"
down_revision: str | None = "0f1501bac9b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("GIAO_DICH_THANH_TOAN", sa.Column("HanQr", sa.DateTime(), nullable=True))
    op.add_column(
        "GIAO_DICH_THANH_TOAN",
        sa.Column("MaThamChieuNganHang", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "GIAO_DICH_THANH_TOAN", sa.Column("ChungTuDoiSoat", sa.String(length=500), nullable=True)
    )
    op.add_column("HOA_DON", sa.Column("SoLanIn", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("HOA_DON", "SoLanIn")
    op.drop_column("GIAO_DICH_THANH_TOAN", "ChungTuDoiSoat")
    op.drop_column("GIAO_DICH_THANH_TOAN", "MaThamChieuNganHang")
    op.drop_column("GIAO_DICH_THANH_TOAN", "HanQr")
    # ### end Alembic commands ###
