"""phase 4 sales dem_order and order fields

Revision ID: 0f1501bac9b8
Revises: 890db4fbb8b6
Create Date: 2026-09-25 15:08:14.770377
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "0f1501bac9b8"
down_revision: str | None = "890db4fbb8b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "DEM_ORDER",
        sa.Column("BusinessDate", sa.Date(), nullable=False),
        sa.Column("SoDaCap", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("BusinessDate", name=op.f("pk_DEM_ORDER")),
    )
    op.add_column("BAN", sa.Column("TrangThai", sa.String(length=20), nullable=False))
    op.add_column("CHI_TIET_ORDER", sa.Column("GhiChu", sa.String(length=500), nullable=True))
    op.alter_column(
        "CHI_TIET_ORDER",
        "SoLuong",
        existing_type=mysql.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.add_column(
        "GIA_BINH_QUAN_THANG",
        sa.Column("TongSoLuongNhap", sa.DECIMAL(precision=18, scale=4), nullable=False),
    )
    op.add_column(
        "GIA_BINH_QUAN_THANG",
        sa.Column("ThoiDiemTinh", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    )
    op.alter_column("LO_NGUYEN_LIEU", "MaChiTietNhap", existing_type=mysql.BIGINT(), nullable=True)
    op.add_column("ORDER", sa.Column("MaOrderHienThi", sa.String(length=30), nullable=True))
    op.add_column("ORDER", sa.Column("LyDoHuy", sa.String(length=500), nullable=True))
    op.create_unique_constraint(op.f("uq_ORDER_MaOrderHienThi"), "ORDER", ["MaOrderHienThi"])
    op.add_column("PHIEU_BEP", sa.Column("NoiDung", sa.String(length=2000), nullable=True))
    op.add_column("PHIEU_BEP", sa.Column("TrangThaiIn", sa.String(length=20), nullable=False))
    op.add_column("PHIEU_BEP", sa.Column("SoLanIn", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("PHIEU_BEP", "SoLanIn")
    op.drop_column("PHIEU_BEP", "TrangThaiIn")
    op.drop_column("PHIEU_BEP", "NoiDung")
    op.drop_constraint(op.f("uq_ORDER_MaOrderHienThi"), "ORDER", type_="unique")
    op.drop_column("ORDER", "LyDoHuy")
    op.drop_column("ORDER", "MaOrderHienThi")
    op.alter_column("LO_NGUYEN_LIEU", "MaChiTietNhap", existing_type=mysql.BIGINT(), nullable=False)
    op.drop_column("GIA_BINH_QUAN_THANG", "ThoiDiemTinh")
    op.drop_column("GIA_BINH_QUAN_THANG", "TongSoLuongNhap")
    op.alter_column(
        "CHI_TIET_ORDER",
        "SoLuong",
        existing_type=sa.Integer(),
        type_=mysql.BIGINT(),
        existing_nullable=False,
    )
    op.drop_column("CHI_TIET_ORDER", "GhiChu")
    op.drop_column("BAN", "TrangThai")
    op.drop_table("DEM_ORDER")
    # ### end Alembic commands ###
