"""initial schema

Revision ID: 890db4fbb8b6
Revises:
Create Date: 2026-09-24 06:17:52.334154
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "890db4fbb8b6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "BAN",
        sa.Column("MaBan", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("TenBan", sa.String(length=50), nullable=False),
        sa.Column("DaXoa", sa.Boolean(), nullable=False),
        sa.Column(
            "TenBan_Active",
            sa.String(length=50),
            sa.Computed("CASE WHEN DaXoa = 1 THEN NULL ELSE TenBan END", persisted=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("MaBan", name=op.f("pk_BAN")),
        sa.UniqueConstraint("TenBan_Active", name=op.f("uq_BAN_TenBan_Active")),
    )
    op.create_table(
        "CAU_HINH_HE_THONG",
        sa.Column("MaCauHinh", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("TenNhaHang", sa.String(length=100), nullable=False),
        sa.Column("DiaChi", sa.String(length=255), nullable=True),
        sa.Column("MauHoaDon", sa.String(length=50), nullable=True),
        sa.Column("NguongTonMacDinh", sa.Integer(), nullable=False),
        sa.Column("GioBatDauBusinessDate", sa.Time(), nullable=False),
        sa.PrimaryKeyConstraint("MaCauHinh", name=op.f("pk_CAU_HINH_HE_THONG")),
    )
    op.create_table(
        "NGUYEN_LIEU",
        sa.Column("MaNguyenLieu", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("TenNguyenLieu", sa.String(length=100), nullable=False),
        sa.Column("DonViTinh", sa.String(length=20), nullable=False),
        sa.Column("SoLuongTon", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.Column("Version", sa.Integer(), nullable=False),
        sa.Column("DaKhoaDonVi", sa.Boolean(), nullable=False),
        sa.Column("MucTonToiThieu", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.Column("SoNgayBaoQuan", sa.Integer(), nullable=True),
        sa.Column("DaXoa", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "MucTonToiThieu >= 0", name=op.f("ck_NGUYEN_LIEU_min_stock_non_negative")
        ),
        sa.CheckConstraint("SoLuongTon >= 0", name=op.f("ck_NGUYEN_LIEU_stock_non_negative")),
        sa.PrimaryKeyConstraint("MaNguyenLieu", name=op.f("pk_NGUYEN_LIEU")),
    )
    op.create_table(
        "NHA_CUNG_CAP",
        sa.Column("MaNhaCungCap", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("TenNhaCungCap", sa.String(length=100), nullable=False),
        sa.Column("SoDienThoai", sa.String(length=20), nullable=True),
        sa.Column("DaXoa", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("MaNhaCungCap", name=op.f("pk_NHA_CUNG_CAP")),
    )
    op.create_table(
        "NHOM_MON",
        sa.Column("MaNhomMon", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("TenNhom", sa.String(length=100), nullable=False),
        sa.Column("ThuTuHienThi", sa.Integer(), nullable=False),
        sa.Column("DaXoa", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("MaNhomMon", name=op.f("pk_NHOM_MON")),
    )
    op.create_table(
        "PHIEU_KIEM_KE",
        sa.Column("MaPhieuKiemKe", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("NgayKiemKe", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("TrangThai", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("MaPhieuKiemKe", name=op.f("pk_PHIEU_KIEM_KE")),
    )
    op.create_table(
        "PHIEU_XUAT_KHO",
        sa.Column("MaPhieuXuat", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("LyDo", sa.String(length=50), nullable=False),
        sa.Column("TrangThai", sa.String(length=20), nullable=False),
        sa.Column("NgayTao", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("MaPhieuXuat", name=op.f("pk_PHIEU_XUAT_KHO")),
    )
    op.create_table(
        "VAI_TRO",
        sa.Column("MaVaiTro", sa.String(length=20), nullable=False),
        sa.Column("TenVaiTro", sa.String(length=50), nullable=False),
        sa.Column("MoTa", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("MaVaiTro", name=op.f("pk_VAI_TRO")),
    )
    op.create_table(
        "CHI_TIET_KIEM_KE",
        sa.Column("MaChiTietKiemKe", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("MaPhieuKiemKe", sa.BigInteger(), nullable=False),
        sa.Column("MaNguyenLieu", sa.BigInteger(), nullable=False),
        sa.Column("TonHeThong", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.Column("TonThucTe", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.Column(
            "ChenhLech",
            sa.DECIMAL(precision=18, scale=4),
            sa.Computed("TonThucTe - TonHeThong", persisted=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["MaNguyenLieu"],
            ["NGUYEN_LIEU.MaNguyenLieu"],
            name=op.f("fk_CHI_TIET_KIEM_KE_MaNguyenLieu"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["MaPhieuKiemKe"],
            ["PHIEU_KIEM_KE.MaPhieuKiemKe"],
            name=op.f("fk_CHI_TIET_KIEM_KE_MaPhieuKiemKe"),
            onupdate="RESTRICT",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("MaChiTietKiemKe", name=op.f("pk_CHI_TIET_KIEM_KE")),
    )
    op.create_table(
        "CHI_TIET_PHIEU_XUAT",
        sa.Column("MaChiTietXuat", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("MaPhieuXuat", sa.BigInteger(), nullable=False),
        sa.Column("MaNguyenLieu", sa.BigInteger(), nullable=False),
        sa.Column("SoLuong", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.Column("GiaVonUocTinh", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["MaNguyenLieu"],
            ["NGUYEN_LIEU.MaNguyenLieu"],
            name=op.f("fk_CHI_TIET_PHIEU_XUAT_MaNguyenLieu"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["MaPhieuXuat"],
            ["PHIEU_XUAT_KHO.MaPhieuXuat"],
            name=op.f("fk_CHI_TIET_PHIEU_XUAT_MaPhieuXuat"),
            onupdate="RESTRICT",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("MaChiTietXuat", name=op.f("pk_CHI_TIET_PHIEU_XUAT")),
    )
    op.create_table(
        "GIA_BINH_QUAN_THANG",
        sa.Column("MaNguyenLieu", sa.BigInteger(), nullable=False),
        sa.Column("Thang", sa.Integer(), nullable=False),
        sa.Column("GiaBinhQuan", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["MaNguyenLieu"],
            ["NGUYEN_LIEU.MaNguyenLieu"],
            name=op.f("fk_GIA_BINH_QUAN_THANG_MaNguyenLieu"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("MaNguyenLieu", "Thang", name=op.f("pk_GIA_BINH_QUAN_THANG")),
    )
    op.create_table(
        "MON_AN",
        sa.Column("MaMon", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("TenMon", sa.String(length=100), nullable=False),
        sa.Column("MaNhomMon", sa.BigInteger(), nullable=True),
        sa.Column("AnThuCong", sa.Boolean(), nullable=False),
        sa.Column("HetNLThuCong", sa.Boolean(), nullable=False),
        sa.Column("HetNLTuDong", sa.Boolean(), nullable=False),
        sa.Column(
            "TrangThai",
            sa.String(length=20),
            sa.Computed(
                "CASE WHEN AnThuCong=1 THEN 'An' WHEN HetNLThuCong=1 OR HetNLTuDong=1 THEN 'Hết nguyên liệu' ELSE 'Hoạt động' END",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.Column("DaXoa", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["MaNhomMon"],
            ["NHOM_MON.MaNhomMon"],
            name=op.f("fk_MON_AN_MaNhomMon"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("MaMon", name=op.f("pk_MON_AN")),
    )
    op.create_table(
        "NGUOI_DUNG",
        sa.Column("MaNguoiDung", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("TenDangNhap", sa.String(length=50), nullable=False),
        sa.Column("MatKhauHash", sa.String(length=255), nullable=False),
        sa.Column("HoTen", sa.String(length=100), nullable=False),
        sa.Column("SoDienThoai", sa.String(length=20), nullable=True),
        sa.Column("MaVaiTro", sa.String(length=20), nullable=False),
        sa.Column("TrangThai", sa.String(length=20), nullable=False),
        sa.Column("NgayTao", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["MaVaiTro"],
            ["VAI_TRO.MaVaiTro"],
            name=op.f("fk_NGUOI_DUNG_MaVaiTro"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("MaNguoiDung", name=op.f("pk_NGUOI_DUNG")),
        sa.UniqueConstraint("TenDangNhap", name=op.f("uq_NGUOI_DUNG_TenDangNhap")),
    )
    op.create_index("ix_NGUOI_DUNG_MaVaiTro", "NGUOI_DUNG", ["MaVaiTro"], unique=False)
    op.create_table(
        "CONG_THUC",
        sa.Column("MaCongThuc", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("MaMon", sa.BigInteger(), nullable=False),
        sa.Column("BusinessDateApDung", sa.DateTime(), nullable=False),
        sa.Column("ThoiDiemHieuLuc", sa.DateTime(), nullable=True),
        sa.Column("ThoiDiemHetHieuLuc", sa.DateTime(), nullable=True),
        sa.Column("LoaiThayDoi", sa.String(length=20), nullable=False),
        sa.Column("TrangThai", sa.String(length=20), nullable=False),
        sa.Column("NguoiTao", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["MaMon"],
            ["MON_AN.MaMon"],
            name=op.f("fk_CONG_THUC_MaMon"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["NguoiTao"],
            ["NGUOI_DUNG.MaNguoiDung"],
            name=op.f("fk_CONG_THUC_NguoiTao"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("MaCongThuc", name=op.f("pk_CONG_THUC")),
    )
    op.create_table(
        "LICH_SU_GIA_MON",
        sa.Column("MaLichSuGia", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("MaMon", sa.BigInteger(), nullable=False),
        sa.Column("Gia", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.Column("BusinessDateApDung", sa.DateTime(), nullable=False),
        sa.Column("ThoiDiemHieuLuc", sa.DateTime(), nullable=True),
        sa.Column("ThoiDiemHetHieuLuc", sa.DateTime(), nullable=True),
        sa.Column("LoaiThayDoi", sa.String(length=20), nullable=False),
        sa.Column("TrangThai", sa.String(length=20), nullable=False),
        sa.Column("NguoiTao", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["MaMon"],
            ["MON_AN.MaMon"],
            name=op.f("fk_LICH_SU_GIA_MON_MaMon"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["NguoiTao"],
            ["NGUOI_DUNG.MaNguoiDung"],
            name=op.f("fk_LICH_SU_GIA_MON_NguoiTao"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("MaLichSuGia", name=op.f("pk_LICH_SU_GIA_MON")),
    )
    op.create_table(
        "NHAT_KY_HE_THONG",
        sa.Column("MaNhatKy", sa.BigInteger(), nullable=False),
        sa.Column("MaNguoiDung", sa.BigInteger(), nullable=False),
        sa.Column("ThoiDiem", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("LoaiThaoTac", sa.String(length=50), nullable=False),
        sa.Column("DoiTuong", sa.String(length=50), nullable=False),
        sa.Column("MaDoiTuong", sa.String(length=50), nullable=False),
        sa.Column("DuLieuTruoc", sa.JSON(), nullable=True),
        sa.Column("DuLieuSau", sa.JSON(), nullable=True),
        sa.Column("LyDo", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["MaNguoiDung"],
            ["NGUOI_DUNG.MaNguoiDung"],
            name=op.f("fk_NHAT_KY_HE_THONG_MaNguoiDung"),
        ),
        sa.PrimaryKeyConstraint("MaNhatKy", name=op.f("pk_NHAT_KY_HE_THONG")),
    )
    op.create_index("ix_NHAT_KY_HE_THONG_ThoiDiem", "NHAT_KY_HE_THONG", ["ThoiDiem"], unique=False)
    op.create_table(
        "ORDER",
        sa.Column("MaOrder", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("BusinessDate", sa.Date(), nullable=False),
        sa.Column("MaBan", sa.BigInteger(), nullable=True),
        sa.Column("LoaiDon", sa.String(length=20), nullable=False),
        sa.Column("TrangThai", sa.String(length=30), nullable=False),
        sa.Column("NguoiTao", sa.BigInteger(), nullable=True),
        sa.Column("NgayTao", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("NgayCapNhat", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "(LoaiDon = 'Tại chỗ' AND MaBan IS NOT NULL) OR (LoaiDon = 'Mang về' AND MaBan IS NULL)",
            name=op.f("ck_ORDER_dine_in_needs_a_table"),
        ),
        sa.ForeignKeyConstraint(
            ["MaBan"],
            ["BAN.MaBan"],
            name=op.f("fk_ORDER_MaBan"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["NguoiTao"],
            ["NGUOI_DUNG.MaNguoiDung"],
            name=op.f("fk_ORDER_NguoiTao"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("MaOrder", name=op.f("pk_ORDER")),
    )
    op.create_index("ix_ORDER_BusinessDate_MaBan", "ORDER", ["BusinessDate", "MaBan"], unique=False)
    op.create_table(
        "PHIEN_CHAT_AI",
        sa.Column("MaPhien", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("MaNguoiDung", sa.BigInteger(), nullable=False),
        sa.Column("NgayTao", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["MaNguoiDung"],
            ["NGUOI_DUNG.MaNguoiDung"],
            name=op.f("fk_PHIEN_CHAT_AI_MaNguoiDung"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("MaPhien", name=op.f("pk_PHIEN_CHAT_AI")),
    )
    op.create_table(
        "PHIEU_NHAP_KHO",
        sa.Column("MaPhieuNhap", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("NgayNhap", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("MaNhaCungCap", sa.BigInteger(), nullable=True),
        sa.Column("TrangThai", sa.String(length=20), nullable=False),
        sa.Column("NguoiTao", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["MaNhaCungCap"],
            ["NHA_CUNG_CAP.MaNhaCungCap"],
            name=op.f("fk_PHIEU_NHAP_KHO_MaNhaCungCap"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["NguoiTao"],
            ["NGUOI_DUNG.MaNguoiDung"],
            name=op.f("fk_PHIEU_NHAP_KHO_NguoiTao"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("MaPhieuNhap", name=op.f("pk_PHIEU_NHAP_KHO")),
    )
    op.create_table(
        "CHI_TIET_CONG_THUC",
        sa.Column("MaCongThuc", sa.BigInteger(), nullable=False),
        sa.Column("MaNguyenLieu", sa.BigInteger(), nullable=False),
        sa.Column("SoLuong", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["MaCongThuc"],
            ["CONG_THUC.MaCongThuc"],
            name=op.f("fk_CHI_TIET_CONG_THUC_MaCongThuc"),
            onupdate="RESTRICT",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["MaNguyenLieu"],
            ["NGUYEN_LIEU.MaNguyenLieu"],
            name=op.f("fk_CHI_TIET_CONG_THUC_MaNguyenLieu"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("MaCongThuc", "MaNguyenLieu", name=op.f("pk_CHI_TIET_CONG_THUC")),
    )
    op.create_table(
        "CHI_TIET_ORDER",
        sa.Column("MaChiTietOrder", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("MaOrder", sa.BigInteger(), nullable=False),
        sa.Column("MaMon", sa.BigInteger(), nullable=False),
        sa.Column("MaLichSuGia", sa.BigInteger(), nullable=True),
        sa.Column("MaCongThuc", sa.BigInteger(), nullable=True),
        sa.Column("SoLuong", sa.BigInteger(), nullable=False),
        sa.Column("DonGia", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.Column("TrangThai", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["MaCongThuc"],
            ["CONG_THUC.MaCongThuc"],
            name=op.f("fk_CHI_TIET_ORDER_MaCongThuc"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["MaLichSuGia"],
            ["LICH_SU_GIA_MON.MaLichSuGia"],
            name=op.f("fk_CHI_TIET_ORDER_MaLichSuGia"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["MaMon"],
            ["MON_AN.MaMon"],
            name=op.f("fk_CHI_TIET_ORDER_MaMon"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["MaOrder"],
            ["ORDER.MaOrder"],
            name=op.f("fk_CHI_TIET_ORDER_MaOrder"),
            onupdate="RESTRICT",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("MaChiTietOrder", name=op.f("pk_CHI_TIET_ORDER")),
    )
    op.create_index(
        "ix_CHI_TIET_ORDER_MaMon_MaOrder", "CHI_TIET_ORDER", ["MaMon", "MaOrder"], unique=False
    )
    op.create_table(
        "CHI_TIET_PHIEU_NHAP",
        sa.Column("MaChiTietNhap", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("MaPhieuNhap", sa.BigInteger(), nullable=False),
        sa.Column("MaNguyenLieu", sa.BigInteger(), nullable=False),
        sa.Column("SoLuong", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.Column("DonGia", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["MaNguyenLieu"],
            ["NGUYEN_LIEU.MaNguyenLieu"],
            name=op.f("fk_CHI_TIET_PHIEU_NHAP_MaNguyenLieu"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["MaPhieuNhap"],
            ["PHIEU_NHAP_KHO.MaPhieuNhap"],
            name=op.f("fk_CHI_TIET_PHIEU_NHAP_MaPhieuNhap"),
            onupdate="RESTRICT",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("MaChiTietNhap", name=op.f("pk_CHI_TIET_PHIEU_NHAP")),
    )
    op.create_table(
        "GIAO_DICH_THANH_TOAN",
        sa.Column("MaGiaoDich", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("MaOrder", sa.BigInteger(), nullable=False),
        sa.Column("SoTien", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.Column("PhuongThuc", sa.String(length=20), nullable=False),
        sa.Column("TrangThai", sa.String(length=20), nullable=False),
        sa.Column("BusinessDate", sa.Date(), nullable=False),
        sa.Column("NgayTao", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["MaOrder"],
            ["ORDER.MaOrder"],
            name=op.f("fk_GIAO_DICH_THANH_TOAN_MaOrder"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("MaGiaoDich", name=op.f("pk_GIAO_DICH_THANH_TOAN")),
    )
    op.create_index(
        "ix_GIAO_DICH_THANH_TOAN_MaOrder_TrangThai",
        "GIAO_DICH_THANH_TOAN",
        ["MaOrder", "TrangThai"],
        unique=False,
    )
    op.create_table(
        "HOA_DON",
        sa.Column("MaHoaDon", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("MaOrder", sa.BigInteger(), nullable=False),
        sa.Column("BusinessDate", sa.Date(), nullable=False),
        sa.Column("ThoiDiemXuat", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("TongTien", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.ForeignKeyConstraint(
            ["MaOrder"],
            ["ORDER.MaOrder"],
            name=op.f("fk_HOA_DON_MaOrder"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("MaHoaDon", name=op.f("pk_HOA_DON")),
        sa.UniqueConstraint("MaOrder", name=op.f("uq_HOA_DON_MaOrder")),
    )
    op.create_index("ix_HOA_DON_ThoiDiemXuat", "HOA_DON", ["ThoiDiemXuat"], unique=False)
    op.create_table(
        "LICH_SU_DOI_BAN",
        sa.Column("MaLichSu", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("MaOrder", sa.BigInteger(), nullable=False),
        sa.Column("MaBanNguon", sa.BigInteger(), nullable=True),
        sa.Column("MaBanDich", sa.BigInteger(), nullable=True),
        sa.Column("NgayTao", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["MaBanDich"],
            ["BAN.MaBan"],
            name=op.f("fk_LICH_SU_DOI_BAN_MaBanDich"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["MaBanNguon"],
            ["BAN.MaBan"],
            name=op.f("fk_LICH_SU_DOI_BAN_MaBanNguon"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["MaOrder"],
            ["ORDER.MaOrder"],
            name=op.f("fk_LICH_SU_DOI_BAN_MaOrder"),
            onupdate="RESTRICT",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("MaLichSu", name=op.f("pk_LICH_SU_DOI_BAN")),
    )
    op.create_table(
        "PHIEU_BEP",
        sa.Column("MaPhieuBep", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("MaOrder", sa.BigInteger(), nullable=False),
        sa.Column("TrangThai", sa.String(length=20), nullable=False),
        sa.Column("NgayTao", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["MaOrder"],
            ["ORDER.MaOrder"],
            name=op.f("fk_PHIEU_BEP_MaOrder"),
            onupdate="RESTRICT",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("MaPhieuBep", name=op.f("pk_PHIEU_BEP")),
    )
    op.create_table(
        "TRUY_VAN_AI",
        sa.Column("MaTruyVan", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("MaPhien", sa.BigInteger(), nullable=False),
        sa.Column("PhamViDuLieu", sa.String(length=50), nullable=True),
        sa.Column("CauHoi", sa.Text(), nullable=False),
        sa.Column("CauSQLSinhRa", sa.Text(), nullable=True),
        sa.Column("TrangThai", sa.String(length=20), nullable=False),
        sa.Column("KetQuaTomTat", sa.Text(), nullable=True),
        sa.Column("ThoiGianPhanHoi", sa.Integer(), nullable=True),
        sa.Column("ThoiDiem", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["MaPhien"],
            ["PHIEN_CHAT_AI.MaPhien"],
            name=op.f("fk_TRUY_VAN_AI_MaPhien"),
            onupdate="RESTRICT",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("MaTruyVan", name=op.f("pk_TRUY_VAN_AI")),
    )
    op.create_index(
        "ix_TRUY_VAN_AI_MaPhien_ThoiDiem", "TRUY_VAN_AI", ["MaPhien", "ThoiDiem"], unique=False
    )
    op.create_table(
        "LO_NGUYEN_LIEU",
        sa.Column("MaLo", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("MaNguyenLieu", sa.BigInteger(), nullable=False),
        sa.Column("MaChiTietNhap", sa.BigInteger(), nullable=False),
        sa.Column("SoLuongConLai", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.Column("TrangThai", sa.String(length=20), nullable=False),
        sa.Column("NgayNhap", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("LoDieuChinhKiemKe", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["MaChiTietNhap"],
            ["CHI_TIET_PHIEU_NHAP.MaChiTietNhap"],
            name=op.f("fk_LO_NGUYEN_LIEU_MaChiTietNhap"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["MaNguyenLieu"],
            ["NGUYEN_LIEU.MaNguyenLieu"],
            name=op.f("fk_LO_NGUYEN_LIEU_MaNguyenLieu"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("MaLo", name=op.f("pk_LO_NGUYEN_LIEU")),
        sa.UniqueConstraint("MaChiTietNhap", name=op.f("uq_LO_NGUYEN_LIEU_MaChiTietNhap")),
    )
    op.create_index(
        "ix_LO_NGUYEN_LIEU_MaNguyenLieu_TrangThai_NgayNhap",
        "LO_NGUYEN_LIEU",
        ["MaNguyenLieu", "TrangThai", "NgayNhap"],
        unique=False,
    )
    op.create_table(
        "GIAO_DICH_KHO",
        sa.Column("MaGiaoDichKho", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("MaNguyenLieu", sa.BigInteger(), nullable=False),
        sa.Column("MaLoNguyenLieu", sa.BigInteger(), nullable=True),
        sa.Column("LoaiGiaoDich", sa.String(length=30), nullable=False),
        sa.Column("SoLuong", sa.DECIMAL(precision=18, scale=4), nullable=False),
        sa.Column("ThoiDiem", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("BusinessDate", sa.Date(), nullable=False),
        sa.Column("MaChiTietNhap", sa.BigInteger(), nullable=True),
        sa.Column("MaChiTietOrder", sa.BigInteger(), nullable=True),
        sa.Column("MaChiTietXuat", sa.BigInteger(), nullable=True),
        sa.Column("MaChiTietKiemKe", sa.BigInteger(), nullable=True),
        sa.Column("NguoiThucHien", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "((LoaiGiaoDich = 'Nhập' AND MaChiTietNhap IS NOT NULL) OR (LoaiGiaoDich IN ('Trừ tự động','Hoàn kho') AND MaChiTietOrder IS NOT NULL) OR (LoaiGiaoDich = 'Xuất thủ công' AND MaChiTietXuat IS NOT NULL) OR (LoaiGiaoDich = 'Điều chỉnh kiểm kê' AND MaChiTietKiemKe IS NOT NULL))",
            name=op.f("ck_GIAO_DICH_KHO_movement_source_matches_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["MaChiTietKiemKe"],
            ["CHI_TIET_KIEM_KE.MaChiTietKiemKe"],
            name=op.f("fk_GIAO_DICH_KHO_MaChiTietKiemKe"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["MaChiTietNhap"],
            ["CHI_TIET_PHIEU_NHAP.MaChiTietNhap"],
            name=op.f("fk_GIAO_DICH_KHO_MaChiTietNhap"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["MaChiTietOrder"],
            ["CHI_TIET_ORDER.MaChiTietOrder"],
            name=op.f("fk_GIAO_DICH_KHO_MaChiTietOrder"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["MaChiTietXuat"],
            ["CHI_TIET_PHIEU_XUAT.MaChiTietXuat"],
            name=op.f("fk_GIAO_DICH_KHO_MaChiTietXuat"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["MaLoNguyenLieu"],
            ["LO_NGUYEN_LIEU.MaLo"],
            name=op.f("fk_GIAO_DICH_KHO_MaLoNguyenLieu"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["MaNguyenLieu"],
            ["NGUYEN_LIEU.MaNguyenLieu"],
            name=op.f("fk_GIAO_DICH_KHO_MaNguyenLieu"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["NguoiThucHien"],
            ["NGUOI_DUNG.MaNguoiDung"],
            name=op.f("fk_GIAO_DICH_KHO_NguoiThucHien"),
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("MaGiaoDichKho", name=op.f("pk_GIAO_DICH_KHO")),
    )
    op.create_index(
        "ix_GIAO_DICH_KHO_MaNguyenLieu_ThoiDiem",
        "GIAO_DICH_KHO",
        ["MaNguyenLieu", "ThoiDiem"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("GIAO_DICH_KHO")
    op.drop_table("LO_NGUYEN_LIEU")
    op.drop_table("TRUY_VAN_AI")
    op.drop_table("PHIEU_BEP")
    op.drop_table("LICH_SU_DOI_BAN")
    op.drop_table("HOA_DON")
    op.drop_table("GIAO_DICH_THANH_TOAN")
    op.drop_table("CHI_TIET_PHIEU_NHAP")
    op.drop_table("CHI_TIET_ORDER")
    op.drop_table("CHI_TIET_CONG_THUC")
    op.drop_table("PHIEU_NHAP_KHO")
    op.drop_table("PHIEN_CHAT_AI")
    op.drop_table("ORDER")
    op.drop_table("NHAT_KY_HE_THONG")
    op.drop_table("LICH_SU_GIA_MON")
    op.drop_table("CONG_THUC")
    op.drop_table("NGUOI_DUNG")
    op.drop_table("MON_AN")
    op.drop_table("GIA_BINH_QUAN_THANG")
    op.drop_table("CHI_TIET_PHIEU_XUAT")
    op.drop_table("CHI_TIET_KIEM_KE")
    op.drop_table("VAI_TRO")
    op.drop_table("PHIEU_XUAT_KHO")
    op.drop_table("PHIEU_KIEM_KE")
    op.drop_table("NHOM_MON")
    op.drop_table("NHA_CUNG_CAP")
    op.drop_table("NGUYEN_LIEU")
    op.drop_table("CAU_HINH_HE_THONG")
    op.drop_table("BAN")
    # ### end Alembic commands ###
