"""p0 fix audit user nullable

Revision ID: 913679962ce8
Revises: 0c722739a556
Create Date: 2026-09-25 15:46:26.027770
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "913679962ce8"
down_revision: str | None = "0c722739a556"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("NHAT_KY_HE_THONG", "MaNguoiDung", existing_type=mysql.BIGINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("NHAT_KY_HE_THONG", "MaNguoiDung", existing_type=mysql.BIGINT(), nullable=False)
    # ### end Alembic commands ###
